### ISSUE TITLE
Error setting up entry name@domain.fr for georide

### ISSUE THREAD

**Issue by bidinaute** [ptimatth/GeorideHA#6]
Hi, and "V"
I am very interested in the module, I installed it from HACS, and at the initial setup, entering my email and password went well.
However I have an error message and I can't use the integration. Thanks for your help, here is the trace:

Logger: homeassistant.config_entries
Source: custom_components/georide/__init__.py:226
Integration: GeoRide ([documentation](https://github.com/ptimatth/GeorideHA), [issues](https://github.com/ptimatth/GeorideHA/issues))
First occurred: 16:55:38 (1 occurrences)
Last logged: 16:55:38

Error setting up entry "monnom@mondomaine.fr" for georide
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/georide/__init__.py", line 98, in async_setup_entry
    await context.init_context(hass)
  File "/config/custom_components/georide/__init__.py", line 247, in init_context
    await self.force_refresh_trackers()
  File "/config/custom_components/georide/__init__.py", line 226, in force_refresh_trackers
    new_georide_trackers = await self._hass.async_add_executor_job(GeoRideApi.get_trackers,
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line 129, in get_trackers
    trackers.append(GeoRideTracker.from_json(json_tracker))
  File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py", line 703, in from_json
    GeoRideSubscription.from_json(json['subscription']) if cls.json_field_protect(json,'subscription') is not None else None,
  File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py", line 962, in from_json
    json['initialDate'],
KeyError: 'initialDate'

**Comment by ptimatth** [comment]
Hi,

Ok, i will look this issue this weekend ;).

Could you please give me some information s:
 What's your GeoRide ?
 Do you have shared trackers ?
 If previous response is ok, what kind of right your friend shared with you ?
Thanks for reply ;)

**Comment by ptimatth** [comment]
A previous version should work until i fix this ;)

**Comment by bidinaute** [comment]
Hi,  thanks for your answer.
I have a Georide 3 not shared.
Best.

**Comment by ptimatth** [comment]
Hi,
I have made a snapshot with a fix for you (i presume because i can't reproduce your bug) you can enable the pre-release in hacs and you can install from it (there is also a lot of new feature for the plugin ;) )  [0.9.0-snapshot33](https://github.com/ptimatth/GeorideHA/releases/tag/0.9.0-snapshot33)

**Comment by bidinaute** [comment]
Hi,

Thanks for your work, but unfortunately, the issue is still here. I use
well the last snapshot :
I can wait, no problem, thx again.

[image: image.png]

Le sam. 19 mars 2022 à 21:53, Matthieu DUVAL ***@***.***> a
écrit :

**Comment by ptimatth** [comment]
Du you have the stack trace please ?
It should be changed

**Comment by bidinaute** [comment]
Here it is. I tried once with a wrong login to see how it works.My name and
domain name are overridden.
If it helps, I use HA  core-2022.3.5 and  supervisor-2022.03.5
Thx

2022-03-20 12:39:48 WARNING (SyncWorker_1) [homeassistant.loader] We found
a custom integration georide which has not been tested by Home Assistant.
This component might cause stability problems, be sure to disable it if you
experience issues with Home Assistant
2022-03-20 12:40:58 ERROR (MainThread) [homeassistant.config_entries] Error
setting up entry ***@***.*** for georide
File "/config/custom_components/georide/__init__.py", line 99, in
async_setup_entry
File "/config/custom_components/georide/__init__.py", line 295, in
init_context
File "/config/custom_components/georide/__init__.py", line 251, in
force_refresh_trackers
new_georide_trackers = await
self._hass.async_add_executor_job(GeoRideApi.get_trackers,
File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line
129, in get_trackers
trackers.append(GeoRideTracker.from_json(json_tracker))
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 703, in from_json
GeoRideSubscription.from_json(json['subscription']) if
cls.json_field_protect(json,'subscription') is not None else None,
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 970, in from_json
GeoRideSubscription_CardInfo.from_json(json['cardInformation'])
2022-03-20 12:45:45 ERROR (MainThread) [homeassistant.config_entries] Error
setting up entry ***@***.*** for georide
File "/config/custom_components/georide/__init__.py", line 99, in
async_setup_entry
File "/config/custom_components/georide/__init__.py", line 295, in
init_context
File "/config/custom_components/georide/__init__.py", line 251, in
force_refresh_trackers
new_georide_trackers = await
self._hass.async_add_executor_job(GeoRideApi.get_trackers,
File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line
129, in get_trackers
trackers.append(GeoRideTracker.from_json(json_tracker))
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 703, in from_json
GeoRideSubscription.from_json(json['subscription']) if
cls.json_field_protect(json,'subscription') is not None else None,
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 970, in from_json
GeoRideSubscription_CardInfo.from_json(json['cardInformation'])
2022-03-20 12:52:47 ERROR (MainThread) [homeassistant.config_entries] Error
setting up entry ***@***.*** for georide
File "/config/custom_components/georide/__init__.py", line 99, in
async_setup_entry
File "/config/custom_components/georide/__init__.py", line 295, in
init_context
File "/config/custom_components/georide/__init__.py", line 251, in
force_refresh_trackers
new_georide_trackers = await
self._hass.async_add_executor_job(GeoRideApi.get_trackers,
File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line
129, in get_trackers
trackers.append(GeoRideTracker.from_json(json_tracker))
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 703, in from_json
GeoRideSubscription.from_json(json['subscription']) if
cls.json_field_protect(json,'subscription') is not None else None,
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 970, in from_json
GeoRideSubscription_CardInfo.from_json(json['cardInformation'])
2022-03-20 13:23:09 WARNING (SyncWorker_9) [georideapilib.api] Login failed
2022-03-20 13:23:09 ERROR (MainThread)
[custom_components.georide.config_flow] Invalid credentials provided,
config not created
2022-03-20 13:23:34 ERROR (MainThread) [homeassistant.config_entries] Error
setting up entry ***@***.*** for georide
File "/config/custom_components/georide/__init__.py", line 99, in
async_setup_entry
File "/config/custom_components/georide/__init__.py", line 295, in
init_context
File "/config/custom_components/georide/__init__.py", line 251, in
force_refresh_trackers
new_georide_trackers = await
self._hass.async_add_executor_job(GeoRideApi.get_trackers,
File "/usr/local/lib/python3.9/site-packages/georideapilib/api.py", line
129, in get_trackers
trackers.append(GeoRideTracker.from_json(json_tracker))
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 703, in from_json
GeoRideSubscription.from_json(json['subscription']) if
cls.json_field_protect(json,'subscription') is not None else None,
File "/usr/local/lib/python3.9/site-packages/georideapilib/objects.py",
line 970, in from_json
GeoRideSubscription_CardInfo.from_json(json['cardInformation'])



Le dim. 20 mars 2022 à 13:04, Matthieu DUVAL ***@***.***> a
écrit :

**Comment by ptimatth** [comment]
OK interesting, thx.
It's weird, it look like you have a particular subscription like a gift card or something like this :/ (i have protected almost all the missing fields unsted of the card information)

**Comment by ptimatth** [comment]
OK i have made a new release  [0.9.0-snapshot34](https://github.com/ptimatth/GeorideHA/releases/tag/0.9.0-snapshot34)

**Comment by bidinaute** [comment]
Awesome Matthieu, that's now OK. thanks a lot

**Comment by bidinaute** [comment]
Awesome, thanks Matthieu !

[image: image.png]

That's OK ! ✌✌✌

Le dim. 20 mars 2022 à 14:08, Matthieu DUVAL ***@***.***> a
écrit :
